DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS "transaction";

CREATE TABLE user (
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  password TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL, 
  phone TEXT UNIQUE,
  name TEXT NOT NULL, 
  upi TEXT UNIQUE, 
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job (
  job_id INTEGER PRIMARY KEY AUTOINCREMENT, 
  payment_id INTEGER, 
  user_id INTEGER,
  title TEXT NOT NULL,
  "location" TEXT NOT NULL,
  detail TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL,
  poster TEXT NOT NULL,
  payment_status INTEGER NULL NULL DEFAULT 0,
  is_accepted INTEGER NOT NULL DEFAULT 0,
  worker INTEGER,
  is_complete INTEGER,
  otp TEXT NOT NULL DEFAULT "0000",
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (user_id),
  FOREIGN KEY (worker) REFERENCES user (user_id)
);


CREATE TABLE "transaction" (
  txn_id INTEGER PRIMARY KEY AUTOINCREMENT, 
  payer INTEGER NOT NULL, 
  payee INTEGER NOT NULL, 
  amount INTEGER NOT NULL,
  job_id INTEGER DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (payer) REFERENCES user (id),
  FOREIGN KEY (payee) REFERENCES user (id)
);

